name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version ${{ github.event.inputs.version }}'     
        required: true
        type: string

jobs:
  release:
    runs-on: macOS-12
    steps:

      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: 'XTLS/Xray-core'
          submodules: 'true'
          path: 'xray'
          
      - name: Setup Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: '1.20'
      
      - name: Setup Gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init
          
      - name: Build xcframework
        run: |
          cd xray
          make
          zip -ry XrayKit.xcframework.zip ./XrayKit.xcframework
          
      - name: Render Template
        run: |
          export TEMP=`shasum -a 256 xray/XrayKit.xcframework.zip`
          export CHECKSUM=${TEMP:0:64}
          cd Templates
          sed -i "_bak" "s/VERSION/${{ github.event.inputs.version }}/g" Package.template
          sed -i "_bak" "s/CHECKSUM/${CHECKSUM}/g" Package.template
          
      - name: Update Package.swift
        run: |
          rm -f Package.swift
          cp ./Templates/Package.template Package.swift
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: XrayKit Release ${{ github.event.inputs.version }}!!!
          commit_user_name: tozik
          commit_user_email: tozika@icloud.com
          tagging_message: ${{ github.event.inputs.version }}
          file_pattern: 'Package.swift'
          
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: ${{ github.event.inputs.version }}
          files: xray/XrayKit.xcframework.zip
